version: '3.9'
services:
    sidenote:
        image: sidenote
        logging:
            options:
                max-size: 1g
        restart: always
        ports:
            - '4000:4000'
    sidenote-front-end:
        image: sidenote-front-end
        logging:
            options:
                max-size: 1g
        restart: always
        ports:
            - '5173:5173'